const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
const SESSION_ID = 'SESSION_ID'
const ADD_TO_CART = 'ADD_TO_CART'
const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
const ADD_FAVORITE = 'ADD_FAVORITE'
const REMOVE_FAVORITE = 'REMOVE_FAVORITE'

export {
  SIGN_IN_SUCCESS,
  SIGN_IN_FAILURE,
  SESSION_ID,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  REMOVE_FAVORITE,
  ADD_FAVORITE
}
