const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_OUT = 'SIGN_OUT';
const UPDATE_CREDENTIALS = 'UPDATE_CREDENTIALS';
const SESSION_ID = 'SESSION_ID';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const ADD_FAVORITE = 'ADD_FAVORITE';
const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

export {
  SIGN_IN_SUCCESS,
  SIGN_OUT,
  UPDATE_CREDENTIALS,
  SESSION_ID,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  REMOVE_FAVORITE,
  ADD_FAVORITE
};
